import PDFDocument from "pdfkit";
import { ReportData } from "./reports.types";
import fs from "fs";

const C = {
  indigo: "#4f46e5",
  indigoDark: "#0f172a",
  success: "#10b981",
  danger: "#ef4444",
  warning: "#f59e0b",
  text: "#1f2937",
  muted: "#9ca3af",
  border: "#e5e7eb",
  bg: "#f9fafb",
  white: "#ffffff",
};

const PAGE_W = 595.28;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;

export async function generatePDF(
  data: ReportData,
  outputPath: string,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: MARGIN,
      bufferPages: true,
      info: {
        Title: data.meta.reportName,
        Author: "DataGuard",
        Subject: `${data.meta.reportType} Security Report`,
      },
    });

    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    // ── Header band ──────────────────────────────────────
    doc.rect(0, 0, PAGE_W, 72).fill(C.indigoDark);
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .fillColor(C.white)
      .text("DataGuard", MARGIN, 18);
    doc
      .fontSize(9)
      .font("Helvetica")
      .fillColor("#818cf8")
      .text("Data Leak Prevention Platform", MARGIN, 42);
    doc
      .fontSize(8)
      .fillColor("#94a3b8")
      .text("CONFIDENTIAL", PAGE_W - MARGIN - 80, 22, {
        width: 80,
        align: "right",
      })
      .text(
        new Date(data.meta.generatedAt).toLocaleDateString(),
        PAGE_W - MARGIN - 80,
        36,
        { width: 80, align: "right" },
      );

    // ── Report title ──────────────────────────────────────
    doc
      .fillColor(C.text)
      .fontSize(18)
      .font("Helvetica-Bold")
      .text(data.meta.reportName, MARGIN, 90);
    const typeLabel =
      data.meta.reportType.charAt(0).toUpperCase() +
      data.meta.reportType.slice(1);
    const rangeLabel =
      data.meta.dateRange === "today"
        ? "Today"
        : data.meta.dateRange === "weekly"
          ? "Last 7 Days"
          : "All Time";
    doc
      .fontSize(9)
      .font("Helvetica")
      .fillColor(C.muted)
      .text(
        `${typeLabel} Report  ·  ${rangeLabel}  ·  Generated by ${data.meta.generatedBy}`,
        MARGIN,
        113,
      );

    // Divider
    doc
      .moveTo(MARGIN, 130)
      .lineTo(PAGE_W - MARGIN, 130)
      .strokeColor(C.border)
      .lineWidth(0.5)
      .stroke();

    // ── Summary stat cards ────────────────────────────────
    const cardW = (CONTENT_W - 12) / 4;
    const cardY = 140;
    const cardH = 68;
    const cards = [
      {
        label: "Total Scans",
        value: String(data.summary.totalScans),
        color: C.indigo,
      },
      {
        label: "Threats Found",
        value: String(data.summary.totalThreats),
        color: data.summary.totalThreats > 0 ? C.danger : C.success,
      },
      {
        label: "Critical Alerts",
        value: String(data.summary.criticalAlerts),
        color: data.summary.criticalAlerts > 0 ? C.danger : C.success,
      },
      {
        label: "Active Policies",
        value: String(data.summary.activePolicies),
        color: C.indigo,
      },
    ];
    cards.forEach((card, i) => {
      const x = MARGIN + i * (cardW + 4);
      doc.roundedRect(x, cardY, cardW, cardH, 6).fill(C.bg);
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .fillColor(card.color)
        .text(card.value, x + 10, cardY + 10, { width: cardW - 20 });
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor(C.muted)
        .text(card.label.toUpperCase(), x + 10, cardY + 42, {
          width: cardW - 20,
          characterSpacing: 0.5,
        });
    });

    // System status
    const isSecure = data.summary.systemStatus === "SECURE";
    const statusColor = isSecure ? C.success : C.danger;
    const statusBg = isSecure ? "#d1fae5" : "#fee2e2";
    doc
      .roundedRect(MARGIN, cardY + cardH + 10, CONTENT_W, 32, 4)
      .fill(statusBg);
    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .fillColor(C.text)
      .text("System Status:", MARGIN + 12, cardY + cardH + 20);
    doc
      .fillColor(statusColor)
      .text(
        data.summary.systemStatus,
        MARGIN + 105,
        cardY + cardH + 20,
      );

    let curY = cardY + cardH + 56;

    // ── Helper: section header ────────────────────────────
    const sectionHeader = (title: string) => {
      if (curY > 720) {
        doc.addPage();
        curY = MARGIN;
      }
      doc
        .fontSize(11)
        .font("Helvetica-Bold")
        .fillColor(C.indigo)
        .text(title.toUpperCase(), MARGIN, curY, {
          characterSpacing: 1,
        });
      curY += 16;
      doc
        .moveTo(MARGIN, curY)
        .lineTo(PAGE_W - MARGIN, curY)
        .strokeColor(C.border)
        .lineWidth(0.5)
        .stroke();
      curY += 10;
    };

    // ── Helper: draw table ────────────────────────────────
    const drawTable = (
      headers: string[],
      colWidths: number[],
      rows: string[][],
    ) => {
      const rowH = 22;
      const headerH = 24;

      // Header row
      if (curY + headerH > 760) {
        doc.addPage();
        curY = MARGIN;
      }
      doc.rect(MARGIN, curY, CONTENT_W, headerH).fill(C.indigo);
      let x = MARGIN;
      headers.forEach((h, i) => {
        doc
          .fontSize(8)
          .font("Helvetica-Bold")
          .fillColor(C.white)
          .text(h.toUpperCase(), x + 6, curY + 7, {
            width: colWidths[i] - 10,
            ellipsis: true,
          });
        x += colWidths[i];
      });
      curY += headerH;

      // Data rows
      rows.forEach((row, ri) => {
        if (curY + rowH > 760) {
          doc.addPage();
          curY = MARGIN;
        }
        const bg = ri % 2 === 0 ? C.white : C.bg;
        doc.rect(MARGIN, curY, CONTENT_W, rowH).fill(bg);
        doc
          .moveTo(MARGIN, curY + rowH)
          .lineTo(PAGE_W - MARGIN, curY + rowH)
          .strokeColor(C.border)
          .lineWidth(0.3)
          .stroke();
        let cx = MARGIN;
        row.forEach((cell, ci) => {
          doc
            .fontSize(8.5)
            .font("Helvetica")
            .fillColor(C.text)
            .text(String(cell ?? "—"), cx + 6, curY + 6, {
              width: colWidths[ci] - 10,
              ellipsis: true,
            });
          cx += colWidths[ci];
        });
        curY += rowH;
      });
      curY += 20;
    };

    // ── Scans ─────────────────────────────────────────────
    if (data.scans && data.scans.length > 0) {
      sectionHeader("Scan Results");
      drawTable(
        [
          "ID",
          "Type",
          "Completed At",
          "Files Scanned",
          "Threats",
          "Status",
        ],
        [40, 80, 140, 90, 70, 79],
        data.scans.map((s) => [
          String(s.id),
          s.type,
          s.time || "—",
          String(s.filesScanned),
          String(s.totalThreats),
          s.status,
        ]),
      );
    }

    // ── Threats ───────────────────────────────────────────
    if (data.threats && data.threats.length > 0) {
      sectionHeader("Detected Threats");
      drawTable(
        [
          "Severity",
          "File Path",
          "Type",
          "Policies Violated",
          "Matches",
          "Status",
        ],
        [60, 160, 80, 110, 50, 39],
        data.threats.map((t) => {
          const shortPath =
            t.filePath.length > 45
              ? "…" + t.filePath.slice(-44)
              : t.filePath;
          return [
            t.severity,
            shortPath,
            t.type,
            t.policiesViolated.join(", ") || "—",
            String(t.matchCount),
            t.status,
          ];
        }),
      );
    }

    // ── Alerts ────────────────────────────────────────────
    if (data.alerts && data.alerts.length > 0) {
      sectionHeader("Active Alerts");
      drawTable(
        ["Severity", "Type", "File Path", "Status", "Time"],
        [60, 100, 200, 60, 79],
        data.alerts.map((a) => {
          const shortPath =
            a.filePath.length > 55
              ? "…" + a.filePath.slice(-54)
              : a.filePath;
          return [a.severity, a.type, shortPath, a.status, a.time];
        }),
      );
    }

    // ── Policies ──────────────────────────────────────────
    if (data.policies && data.policies.length > 0) {
      sectionHeader("Active Policies");
      drawTable(
        ["Name", "Type", "Pattern", "Status"],
        [160, 60, 220, 59],
        data.policies.map((p) => [
          p.name,
          p.type,
          p.pattern,
          p.status,
        ]),
      );
    }

    // ── Recommendations ───────────────────────────────────
    if (data.recommendations && data.recommendations.length > 0) {
      sectionHeader("Recommendations");
      data.recommendations.forEach((rec, i) => {
        if (curY + 30 > 760) {
          doc.addPage();
          curY = MARGIN;
        }
        doc
          .roundedRect(MARGIN, curY, CONTENT_W, 26, 3)
          .fill("#eff6ff");
        doc
          .fontSize(8.5)
          .font("Helvetica-Bold")
          .fillColor(C.indigo)
          .text(`${i + 1}.`, MARGIN + 8, curY + 8);
        doc
          .font("Helvetica")
          .fillColor(C.text)
          .text(rec, MARGIN + 22, curY + 8, {
            width: CONTENT_W - 30,
          });
        curY += 32;
      });
      curY += 8;
    }

    // ── Audit trail ───────────────────────────────────────
    if (data.auditTrail) {
      sectionHeader("Audit Trail");
      drawTable(
        ["Metric", "Value"],
        [260, 239],
        [
          [
            "Total Events Logged",
            String(data.auditTrail.totalEventsLogged),
          ],
          [
            "Data Retention Period",
            data.auditTrail.dataRetentionPeriod,
          ],
          [
            "Last Audit Date",
            new Date(data.auditTrail.lastAuditDate).toLocaleString(),
          ],
        ],
      );
    }

    // ── Footer on every page ──────────────────────────────
    const pageCount = (doc as any).bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc
        .moveTo(MARGIN, 818)
        .lineTo(PAGE_W - MARGIN, 818)
        .strokeColor(C.border)
        .lineWidth(0.5)
        .stroke();
      doc
        .fontSize(7.5)
        .font("Helvetica")
        .fillColor(C.muted)
        .text(
          "DataGuard Confidential Report — Do not distribute without authorization",
          MARGIN,
          824,
          { width: CONTENT_W / 2 },
        );
      doc.text(
        `Page ${i + 1} of ${pageCount}`,
        MARGIN + CONTENT_W / 2,
        824,
        { width: CONTENT_W / 2, align: "right" },
      );
    }

    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });
}
